import Image from 'next/image'
import { Rajdhani } from 'next/font/google'

// import css file
import './styles/globals.css'
import styles from './styles/layout.module.css'

// import component
import Navbar from '@/components/Navbar'

import menu_background from "@/assets/images/menu_background.jpeg"

// meta data
const rajdhani = Rajdhani({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Battlefield 4',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={rajdhani.className}>
      <body className={styles.body}>
        <div className={styles.bgImageBox}>
          <Image
            alt="Authorization Background"
            src={menu_background}
            className={styles.bgImage}
            priority
          />
        </div>
        <main className={styles.mainScreen}>
          <div className={styles.leftScreen}>
            left nav
          </div>

          <div className={styles.centerScreen}>
            <div className={styles.topScreen}>
              <Navbar />
            </div>
            <div className={styles.content}>
              {children}
            </div>
          </div>

          <div className={styles.rightScreen}>
            right nav
          </div>
        </main>
      </body>
    </html>
  )
}
